export const HOME_ACTION_SHORTCUTS = [
  {
    key: 'add-channel',
    title: '1. 새 채널 등록',
    description: '소재를 모을 채널을 온라인 저장소(Azure DB)의 채널 목록에 저장합니다. 저장만으로 영상 수집은 실행하지 않습니다.',
    hint: '채널 등록 화면 열기',
    dataFlowLabels: ['온라인 저장소(Azure DB)의 채널 저장', '영상 수집 없음'],
    iconName: 'plus',
    actionName: 'openAddChannel',
    className: 'border-indigo-400/20 bg-indigo-500/10 hover:border-indigo-300/50 hover:bg-indigo-500/15',
    titleClassName: 'text-indigo-200',
    hintClassName: 'text-indigo-300',
    iconClassName: 'text-indigo-300',
    iconHoverClassName: 'group-hover:scale-110',
  },
  {
    key: 'vault',
    title: '2. 수집 영상 목록',
    description: '온라인 저장소(Azure DB)에 이미 보관된 수집 영상 정보만 열어 후보를 고릅니다. 새 YouTube API 호출은 없습니다.',
    hint: '온라인 저장소(Azure DB) 조회 화면 열기',
    dataFlowLabels: ['온라인 저장소(Azure DB) 조회', '새 API 호출 없음'],
    iconName: 'bookmark',
    actionName: 'openVault',
    className: 'border-blue-400/20 bg-blue-500/10 hover:border-blue-300/50 hover:bg-blue-500/15',
    titleClassName: 'text-blue-200',
    hintClassName: 'text-blue-300',
    iconClassName: 'text-blue-300',
    iconHoverClassName: 'group-hover:scale-110',
  },
  {
    key: 'selected-scan',
    title: '3. 필요할 때 새 영상 수집',
    description: '새 데이터가 필요할 때만 체크한 운영중 채널을 YouTube API로 확인합니다.',
    hint: 'YouTube API 호출 작업',
    dataFlowLabels: ['YouTube API 가능', '온라인 저장소(Azure DB)의 수집 영상 정보 갱신 가능'],
    iconName: 'refresh',
    actionName: 'openSelectedScan',
    className: 'border-emerald-400/20 bg-emerald-500/10 hover:border-emerald-300/50 hover:bg-emerald-500/15',
    titleClassName: 'text-emerald-200',
    hintClassName: 'text-emerald-300',
    iconClassName: 'text-emerald-300',
    iconHoverClassName: 'group-hover:rotate-45',
  },
  {
    key: 'discovery-links',
    title: '4. 발견 링크 저장',
    description: '외부에서 본 URL을 온라인 발견함(Azure DB)에 저장하고 필요하면 제작 후보로 표시합니다.',
    hint: '자동 수집 없이 URL만 저장',
    dataFlowLabels: ['온라인 발견함(Azure DB) 저장', '자동 수집 없음'],
    iconName: 'link',
    actionName: 'openDiscoveryLinks',
    className: 'border-amber-400/20 bg-amber-500/10 hover:border-amber-300/50 hover:bg-amber-500/15',
    titleClassName: 'text-amber-200',
    hintClassName: 'text-amber-300',
    iconClassName: 'text-amber-300',
    iconHoverClassName: 'group-hover:scale-110',
  },
];

export const HOME_WORKSPACE_SHORTCUTS = [
  {
    key: 'keyword-explorer',
    title: '키워드 탐색',
    description: '현재 불러온 수집 영상의 제목과 채널명에서 찾거나, 필요할 때 검색 버튼으로 YouTube의 새 영상·채널 후보를 찾습니다.',
    hint: '기존 수집 영상 검색 · 새 YouTube 후보 검색',
    dataFlowLabels: ['YouTube API 호출 없음', '검색 버튼은 YouTube API 사용'],
    iconName: 'search',
    actionName: 'openKeywordExplorer',
    className: 'border-cyan-400/20 bg-cyan-500/10 hover:border-cyan-300/50 hover:bg-cyan-500/15',
    titleClassName: 'text-cyan-200',
    hintClassName: 'text-cyan-300',
    iconClassName: 'text-cyan-300',
    iconHoverClassName: 'group-hover:scale-110',
  },
  {
    key: 'tag-vault',
    title: '채널 태그별 보기',
    description: '기존 채널 태그로 채널을 묶고, 온라인 저장소(Azure DB)에서 필요한 수집 영상 정보를 확인합니다.',
    hint: '채널 태그별 소재 묶음 열기',
    dataFlowLabels: ['기존 채널 태그', '자동 수집 없음'],
    iconName: 'tags',
    actionName: 'openTagVault',
    className: 'border-emerald-400/20 bg-emerald-500/10 hover:border-emerald-300/50 hover:bg-emerald-500/15',
    titleClassName: 'text-emerald-200',
    hintClassName: 'text-emerald-300',
    iconClassName: 'text-emerald-300',
    iconHoverClassName: 'group-hover:scale-110',
  },
  {
    key: 'upload-calendar',
    title: '업로드 캘린더',
    description: '온라인 저장소(Azure DB)의 제작 기록에 저장된 목표 업로드 날짜를 달력에서 확인합니다.',
    hint: '제작 후보 일정 달력 열기',
    dataFlowLabels: ['온라인 저장소(Azure DB) 일정 조회', '데이터 변경 없음'],
    iconName: 'calendar',
    actionName: 'openUploadCalendar',
    className: 'border-amber-400/20 bg-amber-500/10 hover:border-amber-300/50 hover:bg-amber-500/15',
    titleClassName: 'text-amber-200',
    hintClassName: 'text-amber-300',
    iconClassName: 'text-amber-300',
    iconHoverClassName: 'group-hover:scale-110',
  },
];
