export const IMPROVEMENT_CHECKPOINT_STATUS = {
  DONE: 'done',
  IN_PROGRESS: 'in_progress',
  DECISION_REQUIRED: 'decision_required',
  PLANNED: 'planned',
  LATER: 'later',
};

export const IMPROVEMENT_STATUS_META = {
  [IMPROVEMENT_CHECKPOINT_STATUS.DONE]: {
    label: '확인 완료',
    tone: 'emerald',
  },
  [IMPROVEMENT_CHECKPOINT_STATUS.IN_PROGRESS]: {
    label: '진행 중',
    tone: 'cyan',
  },
  [IMPROVEMENT_CHECKPOINT_STATUS.DECISION_REQUIRED]: {
    label: '결정 필요',
    tone: 'amber',
  },
  [IMPROVEMENT_CHECKPOINT_STATUS.PLANNED]: {
    label: '진행 예정',
    tone: 'indigo',
  },
  [IMPROVEMENT_CHECKPOINT_STATUS.LATER]: {
    label: '나중에',
    tone: 'slate',
  },
};

export const CREATOR_OS_MENU_ROLE_AUDIT = [
  { section: '디스커버리 탐색', menu: '오늘의 레이더', role: '오늘 볼 채널과 수집 영상에서 만들 소재를 결정', dataBoundary: 'Azure DB 조회·판단 기록 저장', verification: '운영 클릭 확인' },
  { section: '디스커버리 탐색', menu: '또터또 탐색', role: '오래된 고성과 영상 후보를 별도 기준으로 탐색', dataBoundary: '불러온 수집 영상 정보 분석', verification: '운영 클릭 확인' },
  { section: '디스커버리 탐색', menu: '키워드 탐색', role: '기존 수집 영상 검색과 YouTube의 새 영상·채널 후보 발굴', dataBoundary: 'Azure DB 조회 탭·명시적 YouTube API 검색 탭 분리', verification: '영상·채널 운영 검수 완료' },
  { section: '디스커버리 탐색', menu: '오늘 볼 채널', role: '오늘 조회할 채널 범위를 선택', dataBoundary: '화면 선택·Azure DB 채널 조회', verification: '운영 클릭 확인' },
  { section: '수집 영상·링크', menu: '수집 영상 목록', role: 'Azure DB에 보관된 수집 영상 정보를 검색·검토', dataBoundary: 'Azure DB 조회·YouTube API 없음', verification: '운영 클릭 확인' },
  { section: '수집 영상·링크', menu: '채널 태그별 보기', role: '수집 영상 목록을 채널 태그 기준으로 좁혀 탐색', dataBoundary: 'Azure DB 조회 결과의 전용 필터·별도 저장 없음', verification: '운영 클릭 확인' },
  { section: '수집 영상·링크', menu: '발견 링크함', role: '외부에서 발견한 링크를 저장·검색·검토하고 상태 관리', dataBoundary: '온라인 발견함(Azure DB) 조회·저장', verification: '운영 클릭 확인' },
  { section: '제작 스튜디오', menu: '제작 후보함', role: '무엇을 만들지 후보와 우선순위를 결정', dataBoundary: '제작 기록 Azure DB 조회·저장', verification: '운영 클릭 확인' },
  { section: '제작 스튜디오', menu: '소재 보관함', role: '나중에 다시 볼 수집 영상 소재를 보관', dataBoundary: '소재 보관함 Azure DB 조회·저장', verification: '운영 클릭 확인' },
  { section: '제작 스튜디오', menu: '대본 작업실', role: '선택한 제작 후보의 분석·구성·대본을 작성', dataBoundary: '대본 기록 Azure DB 조회·저장', verification: '운영 클릭 확인' },
  { section: '제작 스튜디오', menu: '업로드 캘린더', role: '제작 후보의 예정일과 준비 상태를 확인', dataBoundary: '제작 기록 Azure DB 조회·저장', verification: '운영 클릭 확인' },
  { section: '오퍼레이션 관제', menu: '채널 운영실', role: '채널 관리·등록·기존 영상 조회·신규 수집 통제', dataBoundary: '화면 이동·Azure DB·YouTube API를 단계별 분리', verification: '운영·로컬 클릭 확인' },
  { section: '오퍼레이션 관제', menu: '최근 수집 상태', role: '최근 수집 결과와 실패 후속 행동 확인', dataBoundary: 'Azure DB 수집 기록 조회·YouTube API 없음', verification: '운영 클릭 확인' },
  { section: '오퍼레이션 관제', menu: '설정', role: '분야·연결 상태·업무 도구 설정 관리', dataBoundary: '브라우저 표시 설정과 Azure DB 저장 분리', verification: '운영 클릭 확인' },
  { section: '업무 도구', menu: '업무 도구함', role: '공식 외부 조사 도구와 개인 링크를 실행', dataBoundary: '외부 링크·Creator OS 자동 저장 없음', verification: '운영 클릭 확인' },
  { section: '인사이트 / 학습', menu: '개선 기록', role: '현재 상태·검수·결정·다음 작업을 추적', dataBoundary: 'Git 기반 읽기 전용 기록', verification: '운영 클릭 확인' },
];

export const CREATOR_OS_IMPROVEMENT_AREAS = [
  {
    id: 'script-workspace',
    title: '대본 작업실',
    section: '제작 스튜디오',
    status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
    priority: 'P1',
    lastReviewedAt: '2026-08-13',
    currentSummary: '제작 후보 영상과 발견 링크 후보를 원본으로 제목, 분석, 구성안, 대본 본문, 진행 단계, 기존 통합 작업 메모와 업로드 예정일을 기존 온라인 저장소(Azure DB)의 videoUserRecords에 저장합니다. 운영에서 입력 유지와 저장·새로고침·재조회·원상복구까지 확인했습니다. AI 연결 전에도 바로 쓸 수 있도록 원본 분석·구성안·대본 본문의 수동 작성 기준을 접이식 안내로 추가했습니다. 각 단계는 5개 점검 질문을 제공하며 펼치기만으로 DB 저장·YouTube API·AI 요청이 실행되지 않습니다. 기존 작업 묶음 복사는 AI 작업 자료 복사로 명확히 하고, 보유 ChatGPT 등 사용자가 선택한 AI에 직접 붙여넣을 안전 요청문과 제작 정보를 함께 복사합니다.',
    targetSummary: '제작 후보의 원본을 분석하고, 구성안을 만든 뒤, 대본을 작성·수정하고 최종본을 확정하는 독립 작업 공간으로 발전시킵니다.',
    nextAction: '배포 후 운영 대본 작업실에서 수동 작성 기준의 기본 접힘·모바일 배치·입력 및 저장 버튼 비간섭을 정기 회귀 검수합니다. AI 보조는 보유 자원과 비용을 확인한 뒤 별도 결정합니다.',
    decisions: [
      '제작 후보함과 통합하지 않고 별도 작업실로 유지합니다.',
      'AI 자동 분석과 대본 생성은 수동 작성 구조가 안정된 뒤 검토합니다.',
      '새 endpoint나 container 없이 기존 videoUserRecords 문서에 구조화 필드를 추가합니다.',
      '수정 이력과 이전 버전 비교는 개인용 MVP 이후에 검토합니다.',
    ],
    checkpoints: [
      {
        id: 'role-definition',
        label: '제작 후보함은 무엇을 만들지, 대본 작업실은 어떻게 만들지 담당하도록 역할 정의',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'workspace-name',
        label: '메뉴와 화면 이름을 대본 작업실로 통일',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'current-scope',
        label: '제목·분석·구성안·본문·진행 단계·기존 통합 메모·업로드 예정일의 현재 범위 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'backend-contract',
        label: '백엔드가 기존 필드와 새 구조화 대본 필드를 함께 보존하도록 계약 확장',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'script-fields',
        label: '영상 분석·구성안·대본 본문·대본 진행 단계의 저장 구조 결정',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'writing-flow',
        label: '분석 → 구성 → 초안 → 수정 → 최종본 작업 흐름 구현',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'production-script-calendar-navigation',
        label: '제작 후보함 → 대본 작업실 → 업로드 캘린더 왕복 이동 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'script-mobile-layout',
        label: '390×844 모바일에서 대본 입력 항목과 가로 넘침 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'script-unsaved-navigation',
        label: '대본 수정 후 다른 메뉴 이동 시 미저장 경고 표시 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'discovery-link-source',
        label: '발견 링크 제작 후보도 대본 작업의 원본으로 연결',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'revision-history',
        label: '대본 수정 이력과 이전 버전 비교',
        status: IMPROVEMENT_CHECKPOINT_STATUS.LATER,
      },
      {
        id: 'ai-assistance',
        label: '후킹·구조 분석과 대본 초안 AI 보조',
        status: IMPROVEMENT_CHECKPOINT_STATUS.LATER,
      },
      {
        id: 'manual-writing-guide',
        label: 'AI 없이 사용할 수 있는 원본 분석·구성안·대본 본문 단계별 점검 기준',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'manual-ai-work-packet',
        label: '기존 제작 작업 묶음에 복제 금지·사실 확인 기준을 포함한 수동 AI 전달 자료',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
    ],
  },
  {
    id: 'navigation-terms',
    title: '메뉴·용어 정리',
    section: '전체 화면',
    status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
    priority: 'P1',
    lastReviewedAt: '2026-08-12',
    currentSummary: '사용자 화면의 레퍼런스 금고 표현을 수집 영상·링크 구역과 수집 영상 목록으로 정리했습니다. 태그별 금고는 별도 보관 장소로 오해되지 않도록 채널 태그별 보기로 바꾸고 전체 수집 영상 목록으로 돌아가는 버튼을 연결했습니다. 운영 전 화면 검수에서 반복되던 내부 H2는 태그로 수집 영상 좁히기와 조사 도구 바로가기로 구체화해 메뉴 제목과 실제 작업 제목을 분리했습니다. 수집 영상 목록의 초기 상태는 선택 채널 수와 불러온 영상 수를 먼저 보여주고, 채널이 없으면 오늘 볼 채널 선택을 강조하며 채널이 있으면 같은 화면에서 Azure DB 조회를 바로 실행하도록 연결했습니다. PR #1083 배포 후 운영에서 선택 0개 안내와 David Fortin 1개 선택 상태의 직접 Azure DB 조회·영상 251개 표시를 확인했습니다. 수집 영상 목록 상단에는 현재 선택한 채널 이름을 최대 5개까지 표시하고 나머지는 개수로 요약해 조회 범위를 바로 확인할 수 있게 했습니다. PR #1085 배포 후 David Fortin 1개 선택·Azure DB 영상 251개 조회 전후에 채널명이 유지되는 것을 운영 화면에서 확인했습니다. 후속 개선으로 선택 채널 변경 버튼, Azure DB 조회 후 채널별 영상 개수, 설명 가능한 추천순, 최근 30일·6개월 이상 10만 조회·또터또 빠른 보기와 모바일 배치를 추가했습니다. PR #1087 운영 검수에서 조회 전 개수가 0으로 보이는 문제를 발견해 PR #1088로 바로잡았고, TechByTosh·David Fortin이 조회 전에는 조회 전, Azure DB 읽기 후에는 95개·251개로 표시되는 것을 확인했습니다. 빠른 보기 결과는 346개 중 최근 30일 11개·오래된 인기 12개·또터또 29개였습니다. 이어서 각 빠른 보기 버튼에 조회 전·조회 후 해당 영상 수를 표시하고, 추천순의 실제 판단 순서를 화면에 설명했습니다. 5개를 초과해 선택한 채널은 접이식 전체 목록에서 모두 확인할 수 있으며 조회 성공 후 실제 0개와 조회 전 상태를 구분합니다. PR #1090 배포 후 6개 채널의 조회 전 표시, 접이식 전체 목록, 추천 기준을 확인하고 Azure DB 읽기 1회로 영상 3,148개를 불러왔습니다. 빠른 보기 개수는 최근 30일 393개·오래된 인기 868개·또터또 230개였고 최근 30일 적용 결과 393개와 일치했습니다. 대량 목록은 카드·리스트 모두 처음 60개만 만들고 사용자가 요청할 때 60개씩 더 표시하도록 보완했습니다. 빠른 보기 개수는 불러온 전체 목록 기준이며 검색·조회수·길이 필터를 함께 쓰면 실제 표시 수가 줄어든다는 설명을 추가했습니다. PR #1092 배포 후 쪼꼬미필름의 Azure DB 영상 정보 1,271개로 카드 60개 → 120개, 리스트 120개, 최근 30일 82개 적용 시 60개 초기화를 확인했습니다. 390px 모의 화면은 가로 넘침이 없었고 콘솔 오류도 없었습니다. 이후 운영 화면에서 넓은 화면의 도구막대 세 구역이 한 줄에 배치되며 검색 영역 너비가 0px로 눌리는 UI 오류를 확인했습니다. 검색·빠른 보기를 주 작업 영역으로 묶고 새 영상 수집을 22rem 별도 열로 분리해 1,912px에서는 964px·352px, 390px에서는 한 열 275px로 안정적으로 표시되도록 보완했습니다. 카드마다 반복되던 일반 영상의 비교 참고 상자를 제거하고 실제 검토 이유가 있는 영상만 한 줄로 표시하며, 영상 검토 도구 상단에 제작 후보함·소재 보관함 결과 위치를 한 번만 안내합니다.',
    targetSummary: '버튼 이름만 보고도 이동·조회·저장·YouTube API 수집 여부를 이해할 수 있도록 모든 화면의 용어를 통일합니다.',
    nextAction: '통합된 향후 기능 4개가 운영 사이드바와 준비중 안내에 정확히 표시되는지 확인합니다. 이후 실제 휴대폰 사용 중 자연 발생 0개 채널과 채널 태그별 보기의 메뉴 중복 체감을 점검합니다.',
    decisions: [
      '영상 파일 자체가 아니라 영상 정보를 다루므로 수집 영상 목록이라는 표현을 사용합니다.',
      '수집 영상 정보와 발견 링크를 함께 묶는 사이드바 구역명은 수집 영상·링크로 표시합니다.',
      'Cloud라는 단독 표현 대신 온라인 저장소(Azure DB)처럼 실제 위치를 함께 표시합니다.',
      '향후 AI 기능은 별도 최상위 메뉴로 늘리지 않고 대본 작업실 확장 도구로 묶습니다.',
      '제작 상태판은 새 화면보다 제작 후보함·대본 작업실·업로드 캘린더의 현재 흐름 안에서 제공합니다.',
    ],
    checkpoints: [
      {
        id: 'collected-video-term',
        label: '저장 영상 표현을 수집 영상 목록 중심으로 변경',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'storage-term',
        label: '온라인 저장소와 Azure DB의 의미를 사용자 안내에 함께 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'remaining-reference-vault',
        label: '화면에 남아 있던 레퍼런스 금고 표현을 실제 기능명으로 정리',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'radar-collected-video-destination',
        label: '오늘의 레이더 이동 버튼을 수집 영상 목록이라는 실제 도착 화면명으로 통일',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'button-destination-audit',
        label: '모든 주요 버튼의 이름과 실제 결과 위치 대조 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'channel-collection-stage-term',
        label: '채널 운영실의 온라인 저장소 조회와 YouTube 새 영상 수집 단계 이름 구분',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'production-script-calendar-route',
        label: '제작 후보함·대본 작업실·업로드 캘린더의 버튼명과 실제 도착 위치 대조',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'recent-scan-channel-route',
        label: '최근 수집 상태에서 선택한 채널의 관리·수집 단계와 분류 탭 연결',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'radar-vault-discovery-route',
        label: '오늘의 레이더·수집 영상 목록·소재 보관함·발견함의 이동과 빈 결과 복구 대조',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'settings-tools-channel-route',
        label: '설정·업무 도구함 왕복과 채널 등록 입력·결과 안내 대조',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'duplicate-workspace-heading',
        label: '채널 태그별 보기·업무 도구함의 반복 H2를 실제 작업 제목으로 구분',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-empty-next-action',
        label: '수집 영상 목록 빈 상태에서 채널 선택·Azure DB 조회·필요 시 신규 수집의 다음 행동 구분',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-selected-channel-names',
        label: '수집 영상 목록 상단에 현재 선택한 채널 이름과 나머지 개수 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-change-selected-channels',
        label: '수집 영상 목록에서 오늘 볼 채널 변경 화면로 바로 이동',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-per-channel-counts',
        label: 'Azure DB 조회 후 선택 채널별 수집 영상 개수 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-recommended-quick-filters',
        label: '설명 가능한 추천순과 최근·오래된 인기·또터또 빠른 보기',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-mobile-scope-controls',
        label: '모바일에서 채널 범위·변경·빠른 필터 버튼을 한 열로 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-quick-filter-counts',
        label: '최근·오래된 인기·또터또 빠른 보기에 조회 전·조회 후 해당 영상 수 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-recommended-sort-explanation',
        label: '추천순 선택 시 또터또·대박 지수·일평균 반응·조회수 판단 순서 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-all-selected-channels',
        label: '5개 초과 선택 채널을 접이식 전체 목록에서 확인',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-zero-result-distinction',
        label: 'Azure DB 조회 전과 조회 성공 후 실제 0개 채널을 구분',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-incremental-results',
        label: '대량 수집 영상 목록을 처음 60개·이후 60개씩 단계 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-filter-result-count-copy',
        label: '필터 결과 수와 실제 단계 표시 카드 수를 혼동하지 않도록 상단 문구 구분',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-quick-count-scope',
        label: '빠른 보기 개수의 전체 목록 기준과 복합 필터 결과 차이 설명',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-toolbar-responsive-layout',
        label: '넓은 화면에서 검색·빠른 보기·새 영상 수집 영역이 눌리지 않도록 도구막대 분리',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-summary-deduplication',
        label: '수집 영상 목록의 반복 제목·중복 수치·항상 펼쳐진 작업 안내 간소화',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'stored-video-load-result-cross-route',
        label: '화면을 이동해도 같은 선택 채널의 Azure DB 조회 완료 상태와 집계 유지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-toolbar-title',
        label: '보관함 도구막대를 실제 역할인 영상 검토 도구로 변경',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'reference-vault-card-decision-density',
        label: '일반 영상의 반복 판단 상자를 제거하고 실제 검토 이유와 결정 결과 위치를 간결하게 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'future-roadmap-consolidation',
        label: '향후 기능 13개를 현재 작업 공간과 연결되는 4개 통합 목적지로 정리하고 기존 경로 보존',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
    ],
  },
  {
    id: 'discovery-consolidation',
    title: '수집 영상 탐색 통합',
    section: '디스커버리·레퍼런스',
    status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
    priority: 'P2',
    lastReviewedAt: '2026-08-12',
    currentSummary: '수집 영상 목록은 전체 검색·검토, 채널 태그별 보기는 같은 수집 영상 정보를 채널 태그 기준으로 좁혀 보는 전용 보기, 또터또 탐색은 오래된 고성과 후보 판단을 담당합니다. 채널 태그별 보기에서 선택 채널을 바꾸고 곧바로 전체 목록으로 자동 이동하면 이전 범위의 영상이 잠시 새 태그 결과처럼 보일 수 있어 자동 이동은 추가하지 않습니다. 대신 `이 태그 채널로 조회 준비 → 수집 영상 목록 불러오기(Azure DB) → 수집 영상 목록에서 현재 필터 확인 후 검토` 순서를 화면에 표시합니다. 태그 준비 뒤 빈 상태와 상단에 같은 Azure DB 조회 버튼이 중복되던 문제는 상단 버튼 하나로 통합했습니다. 목록 이동은 기존 필터를 유지하므로 `전체 수집 영상` 대신 `수집 영상 목록`으로 정확히 표시합니다. 수집 영상 목록의 모바일 도구는 기본 필터·정렬·보기와 선택 상태의 세 묶음으로 재배치하고 검색 입력이 남은 너비를 사용하도록 정리했습니다. 목록으로 돌아왔을 때 남아 있는 화면 필터는 개수뿐 아니라 검색어·조회수·길이·빠른 보기 이름을 함께 표시합니다. 채널 태그별 보기의 대량 결과도 처음 60개만 만들고 60개씩 더 표시할 수 있으며 더 보기는 DB/API를 호출하지 않습니다. 현재 선택 채널 범위의 Azure DB 조회가 성공한 경우에만 영상·필터 결과·선택 수·전체 수를 표시하며, 채널 선택 변경·전체 해제·조회 실패 때는 이전 범위 영상을 숨깁니다. 390px에서 매우 긴 검색어가 적용 필터 배지의 폭을 밀지 않도록 배지 폭을 화면 안으로 제한하고 단어를 여러 줄로 표시합니다.',
    targetSummary: '메뉴 이름과 화면 안내만으로 전체 목록·전용 필터·독립 판단 화면의 차이를 이해할 수 있게 유지합니다.',
    nextAction: '배포 후 운영 390px 수집 영상 목록에서 긴 검색어 필터 배지의 줄바꿈을 확인합니다. 이후 실제 휴대폰 사용 중 자연 발생 0개 채널과 채널 태그별 보기의 메뉴 중복 여부를 점검합니다.',
    decisions: [
      '또터또 탐색은 오래된 고성과 영상을 찾는 판단 목적이 명확하므로 독립 화면을 유지하는 방향을 권장합니다.',
      '채널 태그별 보기는 새 보관함이 아니라 수집 영상 목록의 태그 전용 보기로 유지하며, 별도 저장소나 자동 수집을 추가하지 않습니다.',
    ],
    checkpoints: [
      {
        id: 'tag-vault-overlap',
        label: '태그별 금고와 수집 영상 목록의 중복 역할 확인',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'tag-filter-decision',
        label: '채널 태그별 보기를 수집 영상 목록의 전용 필터 화면으로 역할 정리',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'ttotto-purpose',
        label: '또터또 탐색의 독립 판단 화면 역할 유지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'tag-channel-load-sequence',
        label: '태그 채널 선택·Azure DB 조회·현재 필터 확인 후 수집 영상 검토 순서 안내',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'tag-channel-single-load-action',
        label: '태그 조회 준비 뒤 Azure DB 불러오기 버튼을 상단 한 곳으로 통합',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'collected-video-mobile-filter-groups',
        label: '모바일 수집 영상 도구를 기본 필터·정렬·보기와 선택 상태로 묶어 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'collected-video-active-filter-labels',
        label: '목록 복귀 뒤 적용 중인 화면 필터의 개수와 실제 조건 이름 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'collected-video-active-filter-mobile-wrap',
        label: '390px에서 긴 검색어 필터 이름을 화면 안에서 여러 줄로 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'tag-vault-progressive-results',
        label: '대량 태그 결과를 60개씩 추가 표시하고 DB/API 비호출 안내',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
    ],
  },
  {
    id: 'youtube-keyword-discovery',
    title: 'YouTube 키워드 영상 찾기',
    section: '디스커버리 탐색',
    status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
    priority: 'P0',
    lastReviewedAt: '2026-08-13',
    currentSummary: '수집 영상과 명시적 YouTube 검색을 분리하고, 영상 찾기와 채널 찾기·비교를 같은 키워드 탐색 안에서 연결했습니다. 검색은 버튼을 눌렀을 때만 YouTube API를 사용하며 결과 전체를 자동 저장하지 않습니다. 영상 검색 결과에서는 영상 후보와 중요 출처 채널 후보를 별도로 고르고, 중복 채널을 합쳐 최대 50개까지 기존 채널 운영실 일괄 등록 검토로 전달합니다. 전달은 주소 입력 준비이며 최종 YouTube 확인과 Azure DB 저장은 사용자가 채널 운영실 버튼을 눌렀을 때만 실행되고 새 영상 수집은 하지 않습니다. 영상·채널 검색 조건, 임시 결과, 필터와 선택은 같은 브라우저 탭의 sessionStorage에서 최대 6시간 새로고침 복구하며 탭을 닫으면 사라집니다. 복구·화면 필터·정렬은 자동 YouTube 재검색이나 Azure DB 조회·저장·localStorage 병합을 실행하지 않습니다. 국가 조건은 시청 가능 지역, 언어 조건은 관련 결과 우선이며 제목 한글 필터는 문자 포함 여부만 판단합니다. 현재 조회수·구독자·대박 비율·하루 평균과 반복 등장 채널은 임시 결과 안의 참고값이며 전체 검색량·실제 성장률·자동 등록 추천 점수가 아닙니다. 운영에서 MS Copilot 결과 25개 중 서로 다른 중요 채널 2개를 채널 운영실로 전달해 2/50개 인식, 결과 복귀, 새로고침 복구와 390px 무가로넘침을 확인했고 검수용 선택은 해제했습니다. 저장 전에는 기존 발견 링크의 영상 ID와 일반 YouTube URL을 함께 대조하고, 조회 중·실패 상태에서는 중복 확인이 끝날 때까지 저장을 막습니다. 배포 후 같은 임시 결과 25개에서 기존 저장 3개·새 선택 0개를 표시했고 390px 가로 넘침과 브라우저 오류가 없음을 확인했습니다.',
    targetSummary: '키워드만 입력해도 새 영상 후보를 비교하고 필요한 항목만 아이디어 창고와 제작 흐름으로 안전하게 이어갈 수 있게 합니다.',
    nextAction: '다음은 선택 영상을 발견 링크함에 담은 뒤 제작 후보로 전환하고 대본 작업실에서 같은 원본이 이어지는 흐름을 읽기 전용·모의 저장으로 먼저 점검합니다. 운영 Azure DB 저장 왕복은 검수 대상을 정한 뒤 별도로 실행합니다.',
    decisions: [
      '기존 수집 영상 검색과 YouTube 신규 검색은 같은 작업 공간의 별도 탭으로 유지합니다.',
      '검색 결과 전체는 자동 저장하지 않고 사용자가 선택한 영상만 발견 링크함에 저장합니다.',
      '자동 입력 검색은 사용하지 않으며 검색과 다음 페이지는 명시적 YouTube API 작업으로 표시합니다.',
      '대박 비율과 하루 평균 조회수는 공식 지표가 아니라 앱 계산 추정값으로 표시합니다.',
      '새 Azure 자원·Cosmos DB container·유료 서비스를 추가하지 않고 기존 자원을 재사용합니다.',
      '채널 검색 결과는 현재 시점의 누적 통계이며 실제 최근 성장률이나 추세로 표시하지 않습니다.',
      '채널 검색 결과에서 자동 등록하지 않고 기존 채널 등록의 확인·저장 단계를 유지합니다.',
      '영상 검색 결과에서도 영상 후보 저장과 출처 채널 등록 검토를 분리해 둘 다 선택할 수 있게 합니다.',
      '채널 운영실 등록 단계에서 영상 검색·채널 검색·채널 일괄 선택 중 어느 경로에서 왔는지 표시하되, 주소와 목록만 미리 채우고 최종 확인·저장은 기존 등록 절차에서 수행합니다.',
      '검색에서 시작한 채널 등록 검토 화면에는 임시 결과와 조건이 유지되는 키워드 탐색으로 바로 돌아가는 버튼을 제공하며, 이 이동은 API나 저장을 실행하지 않습니다.',
      '검색 지역은 해당 국가에서 시청 가능한 결과, 우선 언어는 관련 결과의 우선순위라는 YouTube API 의미를 그대로 안내하며 제작 국가·엄격한 언어 제한으로 표현하지 않습니다.',
      '대한민국·한국어 우선 빠른 설정은 선택값만 바꾸며 검색 버튼을 누르기 전에는 YouTube API를 호출하지 않습니다.',
      '영상 찾기와 채널 찾기 사이를 처음 전환할 때 비어 있는 대상 화면에는 검색어·지역·언어만 이어주고, 기존 결과가 있으면 덮어쓰지 않습니다.',
      '채널 결과 정렬은 이미 받은 결과에만 적용하며 정렬 변경으로 YouTube API를 다시 호출하지 않습니다.',
      '채널 설정 국가는 채널 운영자가 YouTube에 등록한 값만 표시하고 미등록 값을 추정하지 않습니다.',
      '등록 상태·채널 국가 유무·비교 선택 필터는 이미 받은 결과만 화면에서 좁히며 YouTube API나 Azure DB를 호출하지 않습니다.',
      '엄격한 언어 전용 필터는 언어 정보가 비어 있는 유효 결과를 숨길 수 있어 추가하지 않고 우선 언어 방식을 유지합니다.',
      '검색 결과 전체나 채널 후보를 자동으로 온라인 저장하지 않고, 사용자가 선택한 영상만 발견 링크함에 저장하며 중요 채널은 등록 검토로 연결합니다.',
      '비교 선택은 최대 4개, 등록 후보 선택은 최대 50개로 분리하고 실제 일괄 등록은 10개 단위로 처리합니다.',
      '일괄 등록은 기존 등록·중복 입력을 재저장하지 않고 채널별 결과를 표시하며 새 영상 수집을 자동 실행하지 않습니다.',
      '`카이온학습`은 개인 업무 지식 습득 목적의 분류이며, 출처 채널 태그와 개별 발견 영상 태그를 별도 데이터로 관리합니다.',
      '선택한 검색 영상만 기존 발견 링크 문서의 `tags`에 저장하며, 검색 결과 전체 자동 저장이나 새 Cosmos DB container는 추가하지 않습니다.',
      '`카이온학습` 채널은 자동 일괄 수집하지 않고 사용자가 고른 채널을 1개씩 명시적으로 수집합니다.',
      '업로드 기간 필터는 최신성 범위를 좁히는 역할로 사용하고, 서로 비슷한 제목·주제를 묶는 기능은 별도 후속 분석으로 분리합니다.',
      '비슷한 주제 1차 묶음은 제목 핵심어 겹침만 화면에서 계산하고, 결과 대부분에 반복되는 공통어·일반 형식어·연도는 제외합니다. 원본 영상·Azure DB 기록을 합치거나 AI·YouTube API를 호출하지 않습니다.',
      '`create·microsoft·online`처럼 서로 다른 기능에도 반복되는 일반 표현은 묶음 기준에서 제외해 실제 기능명·업무 대상이 두 개 이상 겹칠 때만 묶습니다.',
      '비슷한 주제 칩을 누르면 해당 묶음만 화면에 표시하고, 같은 칩을 다시 누르거나 검색 조건을 바꾸면 전체 결과로 돌아갑니다.',
      '묶음 대표는 별도 종합 점수를 만들지 않고 현재 사용자가 선택한 정렬에서 가장 먼저 나온 영상으로 표시합니다.',
      '기간 검색의 다음 페이지는 첫 검색의 계산된 시작 시각과 API 검색 조건을 그대로 유지하며, 최소 조회수는 받은 결과의 화면 필터로만 적용합니다.',
      '외부 관심도는 새 트렌드 API를 만들지 않고 기존 Google Trends·네이버 공식 도구로 직접 확인하며, Google Trends에는 현재 YouTube 검색 지역을 전달합니다.',
      '현재 조회수·구독자·게시 후 하루 평균만으로 급상승이나 실제 성장률을 자동 판정하지 않습니다.',
      '최근 7일·30일·60일과 평균 조회수·출처 채널 수는 현재 받아온 임시 검색 결과만 화면에서 계산하며 YouTube 전체 검색량이나 시장 추세로 표현하지 않습니다.',
      '같은 임시 결과에 2개 이상 영상이 나온 미등록 출처 채널은 최대 3개까지 반복 등장 채널로 모으되, 반복 횟수를 성장률이나 자동 등록 추천 점수로 사용하지 않습니다.',
      '한글 포함 제목 필터는 현재 받은 결과의 제목 문자만 화면에서 구분하며 실제 음성·자막 언어나 YouTube의 공식 언어 판정으로 표현하지 않습니다.',
      '영상 검색의 화면 필터·현재 결과 정렬과 선택 영상 저장 설정은 별도 영역으로 구분하고, 영상·채널 검색의 로그인 연결 오류에는 기존 Microsoft 로그인 복구 안내를 재사용합니다.',
      '영상 검색의 출처 채널 후보는 영상 후보와 별도로 최대 50개까지 선택하고, 기존 채널 운영실 일괄 등록 검토에 주소만 전달합니다.',
      'YouTube 임시 검색 세션은 같은 브라우저 탭의 sessionStorage에서 최대 6시간 새로고침 복구하며 자동 재검색·Azure DB 저장·localStorage 병합은 하지 않습니다.',
      '발견 링크 중복은 linkedVideoId와 YouTube watch·youtu.be·shorts·live·embed URL의 영상 ID를 함께 대조하고, 기존 목록 조회가 끝나지 않았거나 실패하면 저장을 잠시 막습니다.',
    ],
    checkpoints: [
      {
        id: 'keyword-source-separation',
        label: '수집 영상에서 찾기와 YouTube에서 새로 찾기의 데이터 출처·API 사용 구분',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-external-trend-tools',
        label: '영상·채널 검색 키워드를 Google Trends·네이버 공식 도구와 연결하고 검색 지역 전달',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-result-evidence-summary',
        label: '현재 받은 영상 결과의 기간 분포·평균 조회수·미등록 출처 채널 요약과 빠른 보기',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-repeated-channel-handoff',
        label: '현재 영상 결과에서 반복 등장한 미등록 출처 채널을 모아 등록 검토로 연결',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-title-script-filter',
        label: '현재 받은 영상 결과를 전체 제목·한글 포함 제목·한글 없는 제목으로 화면에서 구분',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-result-tools-clarity',
        label: '결과 좁히기·적용 필터·현재 결과 정렬과 선택 영상 저장 설정을 분리하고 영상·채널 검색 로그인 복구 연결',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-video-source-channel-bulk-selection',
        label: '영상 검색 출처 채널을 중복 없이 최대 50개 선택해 채널 운영실 일괄 등록 검토로 전달',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-session-refresh-recovery',
        label: '같은 브라우저 탭에서 YouTube 임시 검색 세션을 최대 6시간 새로고침 복구',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-backend-contract',
        label: 'API 키를 서버에 유지하는 수동 영상 검색·상세 통계 결합 endpoint와 자동 테스트',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-filters-results',
        label: '검색 지역·우선 언어·기간·길이·조회수·정렬 조건과 실제 적용 조건·임시 결과 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-pagination-criteria-stability',
        label: '기간 검색의 다음 25개 요청에서 첫 검색의 시작 시각·국가·언어·길이·정렬 조건 유지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'purpose-specific-upload-date-filters',
        label: '새 YouTube 검색·수집 영상 검색·또터또 목적에 맞춘 업로드 기간 필터',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'local-similar-topic-groups',
        label: '수집 영상 검색·또터또의 비슷한 주제 묶음·일반 플랫폼 표현 과대 분류 차단·선택 모아보기·현재 정렬 대표 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-discovery-handoff',
        label: '선택한 영상만 발견 링크함에 저장하고 영상 ID·일반 YouTube URL 중복 표시 및 조회 실패 시 저장 차단',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-live-round-trip',
        label: '운영 검색 1회·결과 표시·발견 링크 1건 저장·재조회·원상복구',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-search',
        label: '키워드 기반 채널 검색·비교·채널 등록 연결',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-video-channel-handoff',
        label: '키워드 영상 검색 결과의 중요 채널을 기존 채널 등록 검토로 연결',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-handoff-context',
        label: '채널 등록 검토 화면에서 영상 검색·채널 검색·일괄 선택의 출발 경로와 저장 전 상태 안내',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-preview-api-boundary',
        label: '채널 확인 버튼의 YouTube API 사용과 Azure DB 저장·영상 수집 비실행 경계 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-preview-mobile-layout',
        label: '390px 채널 주소 입력칸과 YouTube API 확인 버튼을 세로 배치해 입력 폭 확보',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-handoff-return',
        label: '채널 등록 검토에서 API 재검색 없이 기존 키워드 탐색 결과로 바로 복귀',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-navigation-session',
        label: '채널 등록 검토 후 돌아와도 재검색 없이 영상·채널 임시 결과와 조건 유지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-convenience-controls',
        label: '대한민국·한국어 빠른 설정과 검색 조건 변경 시 재검색 필요 안내',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-video-channel-common-filter-handoff',
        label: '영상 찾기와 채널 찾기 전환 시 검색어·지역·언어 조건 이어받기와 기존 결과 보호',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-result-local-sort',
        label: '채널 결과의 화면 정렬과 채널 설정 국가 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-result-view-filters',
        label: '1~2. 등록 상태·채널 국가 유무·비교 선택만 보기와 화면 필터 초기화',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-comparison-summary',
        label: '3. 비교 선택 채널의 핵심 수치·등록·국가 상태 요약 보강',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-comparison-clear',
        label: '4. 비교 선택 전체 해제와 최대 4개 안내 보강',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-video-channel-registration-filter',
        label: '5. 영상 검색 결과를 출처 채널 등록 여부로 화면 필터',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-video-action-hierarchy',
        label: '6. 영상 후보 저장과 출처 채널 등록 검토의 버튼 우선순위 정돈',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-mobile-controls',
        label: '7. 모바일 검색 결과 필터·정렬·작업 버튼 밀도 점검',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-session-regression',
        label: '8. 화면 왕복 시 검색 조건·결과·화면 필터 유지 회귀 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-strict-language-filter-decision',
        label: '9. 엄격한 언어 전용 필터는 추가하지 않고 우선 언어 방식 유지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.LATER,
      },
      {
        id: 'youtube-search-candidate-storage-decision',
        label: '10. 검색 결과 전체 자동 저장 없이 선택한 영상·채널만 기존 흐름으로 연결',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-decision-record',
        label: '두 번째 1. 언어·검색 결과 저장 운영 기준을 개선 기록에 확정',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-video-result-clear',
        label: '두 번째 2. 영상 임시 검색 결과를 사용자가 직접 정리',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-result-clear',
        label: '두 번째 3. 채널 임시 검색 결과와 비교 선택을 사용자가 직접 정리',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-result-clear-criteria-retention',
        label: '두 번째 4. 임시 결과를 지워도 입력한 검색 조건 유지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-result-clear-transient-reset',
        label: '두 번째 5. 결과 정리 시 선택·비교·페이지 토큰·화면 필터 초기화',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-result-clear-boundary-copy',
        label: '두 번째 6. 결과 정리가 YouTube API·Azure DB·기존 발견 링크를 바꾸지 않는다는 안내',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-result-clear-mobile',
        label: '두 번째 7. 모바일 결과 정리 버튼 배치와 가로 넘침 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-result-clear-session',
        label: '두 번째 8. 결과 정리 후 화면 왕복에서도 빈 임시 세션 유지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-registration-return-regression',
        label: '두 번째 9. 채널 등록 검토 왕복과 결과 정리의 상호 영향 회귀 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-search-session-expiration',
        label: '두 번째 10. 임시 검색 세션 자동 만료·영구 후보함은 개인용 MVP 이후 검토',
        status: IMPROVEMENT_CHECKPOINT_STATUS.LATER,
      },
      {
        id: 'youtube-comparison-registration-action',
        label: '세 번째 1. 비교 요약에서 중요 채널 등록 검토로 바로 이동',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-comparison-original-link',
        label: '세 번째 2. 비교 요약에서 YouTube 채널 원본 바로 열기',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-comparison-item-remove',
        label: '세 번째 3. 비교 요약에서 채널별 비교 선택 해제',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-comparison-registered-guard',
        label: '세 번째 4. 이미 등록된 채널의 중복 등록 검토 차단',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-comparison-action-boundary',
        label: '세 번째 5. 비교 요약 작업의 화면 이동·API·Azure DB 영향 안내',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-comparison-action-mobile',
        label: '세 번째 6. 모바일 비교 요약 작업 버튼 배치와 가로 넘침 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-comparison-registration-return',
        label: '세 번째 7. 비교 요약 등록 검토 왕복 뒤 검색 결과·비교 선택 유지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-comparison-registered-refresh',
        label: '세 번째 8. 등록 채널 목록 갱신 시 비교 요약의 등록 상태 즉시 반영',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-comparison-action-accessibility',
        label: '세 번째 9. 비교 요약 작업 버튼·링크의 키보드 접근과 명확한 이름 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-batch-registration-decision',
        label: '세 번째 10. 여러 검색 채널의 일괄 YouTube 확인·Azure DB 등록',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-registration-selection-separation',
        label: '네 번째 1~2. 비교 최대 4개와 등록 후보 최대 50개 선택 분리',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-channel-search-page-size',
        label: '네 번째 3. 채널 검색 기본 25개·다음 25개 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-bulk-registration-handoff',
        label: '네 번째 4. 선택 후보를 채널 운영실 일괄 등록 검토로 전달',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-bulk-registration-limit',
        label: '네 번째 5. 51개 이상 일괄 등록 요청의 프론트·백엔드 사전 차단',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-bulk-registration-batches',
        label: '네 번째 6. 최대 50개를 10개 단위로 YouTube 확인·Azure DB 처리',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-bulk-registration-deduplication',
        label: '네 번째 7. 기존 등록 채널·같은 요청 중복 입력 재저장 방지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-bulk-registration-results',
        label: '네 번째 8. 새로 저장·기존 등록·중복 입력·실패의 채널별 결과 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-bulk-registration-local-verification',
        label: '네 번째 9. 모바일 배치·화면 왕복·검색 세션 유지 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-bulk-registration-live-write',
        label: '네 번째 10. 사용자가 선택한 실제 채널 일괄 등록·Azure DB 재조회',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-learning-purpose-tags',
        label: 'MS Copilot 선택 영상·출처 채널을 카이온학습으로 분리 저장하고 Azure DB 재조회',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'kaion-learning-first-channel-collection',
        label: 'Mike Tholfsen 1개 채널 신규 수집 1회와 Azure DB 250개 재조회',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'youtube-trend-history',
        label: '시간별 통계 기록을 바탕으로 실제 조회 증가량과 추세 비교',
        status: IMPROVEMENT_CHECKPOINT_STATUS.LATER,
      },
    ],
  },
  {
    id: 'data-safety',
    title: '데이터·API 안전 검수',
    section: '전체 데이터 흐름',
    status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
    priority: 'P1',
    lastReviewedAt: '2026-08-12',
    currentSummary: '온라인 저장소(Azure DB) 조회와 YouTube 새 영상 수집을 분리하고, 중요한 저장 버튼에는 데이터 변경 여부를 안내합니다. 최근 수집 상태 화면에는 현재 화면의 Azure DB 읽기, 사용자가 직접 실행하는 YouTube 신규 수집과 DB 갱신, 아직 제공하지 않는 정확한 API 쿼터 장부를 세 칸으로 구분했습니다. 과거 목록 수동 수집의 자동 반복·예약 없음 안내도 최신 영상 예약 수집 이력과 혼동되지 않도록 범위를 명시했습니다. 야간 Timer가 모든 활성 채널을 자동 수집하고 전체 영상 대박지수를 반복 저장하던 문제를 백엔드 PR #28로 수정·배포했습니다. 2026-08-09 새벽 3시 첫 운영 실행은 341ms 만에 대상 채널 0·실패 0·신규 0·통계 갱신 0·영상 저장 0으로 완료됐습니다. 같은 15분 구간 비교에서 Cosmos 요청은 13,296건에서 4건, 429는 7,161건에서 0건, Upsert는 13,146건에서 0건, RU는 61,464에서 4로 줄었습니다. 등록 채널 21개는 모두 수동 취급 상태이며 active+auto 채널은 0개입니다. 프론트는 현재 선택 채널 키와 Azure DB 조회 성공 키가 일치하는 영상만 중앙 데이터 관문에서 업무 화면에 전달해, 레이더·수집 영상 목록·채널 태그별 보기·또터또·수집 영상 검색에 이전 범위 결과가 섞이지 않게 합니다. 채널 범위를 바꾼 뒤 늦게 도착한 이전 Azure DB 조회 응답도 중앙 영상·결과·진행 상태를 덮어쓰지 않도록 요청 순서를 함께 검증합니다. 운영에서 TechByTosh 95개 조회 후 David Fortin으로 전환하자 다섯 화면이 조회 전 0개 상태로 함께 바뀌었고, David Fortin 251개 재조회 뒤 레이더·목록·태그·또터또 20개·키워드 탐색이 새 범위로 일치했습니다.',
    targetSummary: '화면 표시, 이동, DB 조회, DB 저장, YouTube API 수집을 모든 핵심 흐름에서 실제 결과까지 확인하고 기록합니다.',
    nextAction: '자동 수집 채널은 0개로 유지합니다. 다음 사용성 점검에서는 실제 모바일 기기의 수집 영상 251개 목록과 자연 발생 0개 채널을 확인하고, Azure 비용·429 이상 징후가 있을 때만 지표를 읽기 전용으로 재점검합니다.',
    decisions: [
      'YouTube 새 영상 수집과 Azure DB 쓰기는 화면 이동 검수와 분리합니다.',
      '실제 저장 왕복 검수는 기존 제작 기록의 원문을 먼저 보존한 뒤 검수하고 즉시 원상복구합니다.',
      'YouTube 실제 수집 검수는 명시적으로 선택한 채널 1개를 한 번만 실행하고, 반복 실행 없이 최근 수집 상태와 Azure DB 재조회로 결과를 확인합니다.',
      '채널의 active 상태는 수동 수집 가능 여부이고, 야간 자동 수집은 collectionMode가 auto로 명시된 경우에만 허용합니다.',
    ],
    checkpoints: [
      {
        id: 'lookup-vs-collection',
        label: 'Azure DB 조회와 YouTube 신규 수집 구분',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'button-safety-copy',
        label: '주요 저장·수집 버튼에 데이터 출처와 변경 여부 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'recent-scan-api-boundary-guide',
        label: '최근 수집 상태에서 Azure DB 조회·YouTube 신규 수집·정확한 쿼터 미제공 범위 구분',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'cloud-round-trip',
        label: 'Azure DB 실제 저장 후 새로고침·재조회 유지 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'single-channel-youtube-collection',
        label: '명시적으로 선택한 채널 1개의 YouTube 신규 수집 1회와 Azure DB 결과 재조회',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'collection-result-feedback',
        label: '수집 실행 화면에서 채널별 신규 수·통계 갱신 수·최근 수집 상태 위치를 즉시 안내',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'tteotteotto-threshold-alignment',
        label: '수집 완료 카드와 또터또 탐색의 후보 기준을 6개월 이상·채널 평균 1.5배 이상으로 통일',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'registered-channel-auto-scan-boundary',
        label: '채널 등록과 야간 자동 수집 승인을 collectionMode로 분리',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'changed-video-single-write',
        label: '통계·대박지수 갱신을 합쳐 변경된 영상만 한 번 저장',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'timer-summary-observability',
        label: '야간 자동 실행에 대상·실패·신규·갱신·저장 건수 요약 로그',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'stored-video-stale-response-guard',
        label: '채널 범위 변경 후 늦게 도착한 이전 Azure DB 조회 응답 무시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'stored-video-scope-live-round-trip',
        label: '운영 채널 A 조회 → 채널 B 전환 → 전 화면 조회 전 상태 → 채널 B 재조회',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
    ],
  },
  {
    id: 'operational-regression',
    title: '업무 시스템 정기 회귀 검수',
    section: '전체 핵심 화면',
    status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
    priority: 'P1',
    lastReviewedAt: '2026-08-11',
    currentSummary: '핵심 화면을 화면 표시, 실제 클릭, 보이는 변화, 결과 위치, 데이터 영향, 오류 복구, 모바일 순서로 점검합니다. Azure DB 제작 기록·업로드 일정 저장 왕복과 Jinxy 단일 채널 YouTube 신규 수집 1회 및 최근 수집 결과 재조회를 완료했습니다. 레이더 전체 작업 기록 삭제 경로를 차단했고, 소재 보관과 제작 후보 원본 용도를 분리했습니다. 현재 불러온 수집 영상 정보가 있으면 소재·제작 화면에 최신 표시 정보를 우선 반영합니다. 제작 기록 저장은 변경 필드만 전송하고 누락 필드를 보존합니다. 모든 제작 진행 기록은 오늘의 레이더에서 숨기고 제작 후보함에서 계속 확인합니다. 제작 후보 상태 저장이 실패하면 이 작업이 방금 만든 제작 전용 원본만 자동 정리하며 기존 소재 기록은 삭제하지 않습니다. 제작 원본 목록이 상위 라우팅 관문과 작업 화면 조립 관문을 모두 지나 후보함·대본 작업실·업로드 캘린더에 전달되도록 복구했고, 운영 제작 후보함에서 영상 1개·링크 1개·작업 항목 2개와 Jinxy 원본 표시를 확인했습니다. 저장·검색·검토·상태 관리를 함께 하는 링크 화면은 단일 저장 동작처럼 보이지 않도록 발견 링크함으로 정리했습니다. 백엔드는 Pull Request에서 Node.js 24 잠금 파일 설치와 전체 테스트만 실행하고 main에서만 기존 Azure Function App을 배포합니다. 프론트 CI는 Azure Static Web Apps 실제 Oryx 빌드와 같은 Node.js 22 계열로 검수합니다. 모바일 작업 탭은 짧은 표시 이름으로 줄바꿈을 줄이고, 수집 영상 키워드 탐색에서 같은 조회 범위의 또터또 후보 화면으로 바로 이어집니다.',
    targetSummary: '배포마다 핵심 업무 흐름의 이름·버튼·결과·데이터 경계를 같은 기준으로 빠짐없이 재확인합니다.',
    nextAction: '배포마다 제작 원본 수와 후보함·대본 작업실·업로드 캘린더의 표시 수가 같은지 읽기 전용 회귀 검수합니다. 2026-07-20 임시 검증 링크는 개인용 운영 흐름의 표본으로 보존합니다. 실제 부분 실패를 강제로 만드는 Azure DB 쓰기·삭제 검수와 다중 브라우저 동시 변경 보호는 별도 결정 뒤 진행합니다.',
    decisions: [
      '버튼 존재와 자동 테스트 통과만으로 운영 확인 완료라고 표시하지 않습니다.',
      'Azure DB 실제 쓰기는 원문 보존과 원상복구가 가능한 대상을 정해 실행하고, YouTube API 신규 수집은 별도 승인 후 실행합니다.',
      '모바일 기준 화면은 390×844이며 페이지 전체 가로 넘침이 없어야 합니다.',
      'Azure 배포의 github_id_token 경고는 입력 제거 시 실제 배포가 실패한 이력이 있어 Azure 인증 방식 결정 전까지 비차단 경고로 유지합니다.',
      'Codex 임시 흐름 검증 2026-07-20 링크는 개발 일지가 아니라 발견 링크→제작 후보 연결을 확인한 운영 표본이며, 개인용 단계에서는 삭제하지 않고 보존합니다.',
    ],
    checkpoints: [
      {
        id: 'radar-collection-regression',
        label: '오늘 볼 채널 → 수집 영상 목록 불러오기 → 오늘의 레이더 복귀',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'collection-vault-discovery-regression',
        label: '수집 영상 목록·소재 보관함·발견함 이동과 빈 결과 복구',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'production-regression',
        label: '제작 후보함 → 대본 작업실 → 업로드 캘린더 왕복',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'settings-tools-regression',
        label: '설정 ↔ 업무 도구함 왕복, 미저장 경고와 데이터 영향 안내',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'channel-add-regression',
        label: '채널 등록 빈 입력 차단, 중복 저장 차단, 오류 후 재시도',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'mobile-regression',
        label: '설정·업무 도구함·채널 등록 포함 핵심 화면 390×844 가로 넘침',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'stale-route-recovery',
        label: '배포 후 오래 열린 탭의 화면 파일 로딩 실패 시 새로고침 안내',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'write-round-trip-regression',
        label: 'Azure DB 실제 저장 후 새로고침·재조회 유지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'schedule-round-trip-regression',
        label: '업로드 예정일 저장 → 캘린더 재조회 → 날짜 미정 원상복구',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'discovery-tools-regression',
        label: '또터또 빈 결과 복구와 키워드 추천어 선택 후 수집 영상 결과 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'recent-operations-route-regression',
        label: '최근 수집 상태의 채널 카드 → 해당 채널이 선택된 채널 운영실 연결',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'discovery-operations-mobile-regression',
        label: '또터또·키워드·최근 수집 상태·채널 운영실 390×844 가로 넘침',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'mobile-workspace-tabs-and-keyword-ttotto-route',
        label: '모바일 작업 탭 간결 표시와 수집 영상 키워드 탐색 → 또터또 화면 이동',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'recent-scan-filter-history-regression',
        label: '최근 수집 상태 검색·조합 필터·정렬·과거 실행 상세 펼치기',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'explicit-channel-scan-safety',
        label: '채널을 선택하지 않으면 YouTube 새 영상 수집을 실행할 수 없도록 차단',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'single-channel-live-scan-regression',
        label: '선택 채널 1개 YouTube 신규 수집 1회 → 최근 수집 상태 → 새로고침 후 Azure DB 재조회',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'production-script-calendar-regression',
        label: '제작 후보 → 대본 작업실 → 업로드 캘린더 → 대본 이어쓰기 왕복',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'collected-video-selection-regression',
        label: '수집 영상 카드·리스트 보기와 다중 선택 후 AI 요청문 작업 막대 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'partial-storage-warning-scope',
        label: '일부 Azure DB 기능 연결 실패가 다른 정상 조회까지 실패한 것처럼 보이지 않도록 경고 범위 표시',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'selected-video-copy-clear-regression',
        label: 'AI 요청문 실제 클립보드 내용·복사 완료 안내·전체 선택 해제',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'mobile-list-guidance',
        label: '390×844 리스트 보기의 제목·조회수·대박 지수·게시일 중심 간결 목록',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'daily-three-minute-regression',
        label: '저장·삭제·YouTube 신규 수집 없는 매일 3분 핵심 회귀 순서',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'daily-readonly-test-command',
        label: '매일 핵심 안전 계약을 한 번에 확인하는 npm run test:daily 자동 검수 명령',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'visible-filter-selection-state',
        label: '적용 필터 수·화면 선택 수 표시와 선택을 유지하는 필터 초기화',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'feature-specific-storage-retry',
        label: '영상 판단 기록·소재 보관함 오류별 Azure DB 읽기 전용 다시 확인',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'storage-retry-pending-state',
        label: 'Azure DB 읽기 재확인 처리 중 표시와 중복 클릭 방지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'storage-retry-result-feedback',
        label: '영상 판단 기록·소재 보관함별 재확인 성공·실패 결과 안내',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'video-search-quick-clear',
        label: '영상 선택을 유지하는 수집 영상 검색어 빠른 지우기',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'mobile-long-title-actions',
        label: '390×844 긴 제목과 소재 보관·제작 후보 버튼 배치 보완',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'daily-readonly-github-check',
        label: 'PR과 main 반영 때 GitHub에서 별도 이름으로 보이는 핵심 읽기 전용 자동 검수',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'deployment-warning-decision-boundary',
        label: 'github_id_token 경고와 실제 배포 성공의 분리 및 변경 보류 기준',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'radar-full-record-clear-protection',
        label: '판단 초기화가 제작 후보·대본·업로드 일정을 포함한 전체 작업 기록을 삭제하지 못하도록 화면 실행 경로 차단',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'scrapbook-production-source-separation',
        label: '소재 보관 해제와 제작 후보 원본 보존을 분리하고 후보함·대본 작업실·업로드 캘린더 연결 유지',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'scrapbook-current-metadata-overlay',
        label: '현재 불러온 수집 영상의 최신 표시 정보를 소재·제작 원본에 비파괴적으로 병합',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'production-record-partial-update-safety',
        label: '대본·일정·제작 상태의 변경 필드만 저장하고 누락 필드는 백엔드에서 보존',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'legacy-production-radar-visibility',
        label: '과거 호환 제작 상태를 포함한 모든 제작 진행 영상을 오늘의 레이더에서 숨기고 제작 후보함에서 계속 확인',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'production-source-failure-rollback',
        label: '제작 후보 상태 저장 실패 시 방금 만든 제작 전용 원본만 자동 정리하고 기존 소재 기록 보호',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'production-source-route-continuity',
        label: '소재 보관함·제작 후보함·대본 작업실·업로드 캘린더의 제작 원본 목록 전달 경로와 후보 수 일치',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'discovery-link-workspace-naming',
        label: '발견 링크 저장·검색·검토·상태 관리를 포함하는 화면 이름을 발견 링크함으로 통일',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'discovery-smoke-link-cleanup-decision',
        label: '운영 발견 링크함의 Codex 임시 흐름 검증 2026-07-20 기록을 개인용 운영 표본으로 보존',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'backend-pr-validation',
        label: '백엔드 Pull Request 사전 테스트와 main 전용 Azure Function 배포 분리',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'frontend-ci-runtime-alignment',
        label: '프론트 Pull Request 검사와 Azure Static Web Apps 실제 빌드의 Node.js 22 계열 일치',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
      {
        id: 'compatibility-facade-audit',
        label: 'functionApi·라우팅 호환 관문을 실제 중복 로직과 구분하고 신규 코드의 도메인 모듈 직접 사용 기준 기록',
        status: IMPROVEMENT_CHECKPOINT_STATUS.DONE,
      },
    ],
  },
];

export const IMPROVEMENT_LOG_LAST_UPDATED = CREATOR_OS_IMPROVEMENT_AREAS.reduce(
  (latestDate, area) => (area.lastReviewedAt > latestDate ? area.lastReviewedAt : latestDate),
  '',
);
