import { useCategories } from './useCategories';
import { useChannelActions } from './useChannelActions';
import { useChannelAddActions } from './useChannelAddActions';
import { useChannelFormState } from './useChannelFormState';
import { useChannelNotesModal } from './useChannelNotesModal';
import { useChannelSelection } from './useChannelSelection';
import { useCloudChannels } from './useCloudChannels';
import { useTagRenameActions } from './useTagRenameActions';

export function useCreatorAppChannelWorkflow({
  setError,
  setLoading,
  setProgressMsg,
  setUpdatingChannelId,
}) {
  const { categories, setCategories } = useCategories();
  const {
    selectedCategoryTab,
    selectedChannelIds,
    setSelectedCategoryTab,
    setSelectedChannelIds,
    toggleChannelSelection,
  } = useChannelSelection(categories[0]);
  const {
    addMode,
    bulkInput,
    bulkLoading,
    bulkResult,
    cancelChannelPreview,
    cancelRenameCategory,
    channelPreview,
    isEditingCategory,
    newCategoryName,
    newChannelInput,
    newChannelLang,
    newChannelNote,
    newChannelTags,
    previewLoading,
    renameLoading,
    renameValue,
    renamingCategory,
    resetBulkAdd,
    setAddMode,
    setBulkInput,
    setBulkLoading,
    setBulkResult,
    setChannelPreview,
    setIsEditingCategory,
    setNewCategoryName,
    setNewChannelInput,
    setNewChannelLang,
    setNewChannelNote,
    setPreviewLoading,
    setRenameLoading,
    setRenameValue,
    startRenameCategory,
    toggleNewChannelTag,
  } = useChannelFormState();
  const {
    savedChannels,
    setSavedChannels,
    channelsLoading,
    loadChannelsFromCloud,
  } = useCloudChannels({ onError: setError });
  const {
    saveChannel,
    bulkCreateChannels,
    deleteChannel,
    updateChannelMetadata,
    saveChannelNote,
  } = useChannelActions({
    setSavedChannels,
    setSelectedChannelIds,
    setUpdatingChannelId,
    setError,
  });
  const {
    handleBulkAdd,
    handlePreviewChannel,
    handleSaveChannel,
  } = useChannelAddActions({
    bulkCreateChannels,
    bulkInput,
    cancelChannelPreview,
    channelPreview,
    loadChannelsFromCloud,
    newChannelInput,
    newChannelLang,
    newChannelNote,
    newChannelTags,
    savedChannels,
    saveChannel,
    setBulkLoading,
    setBulkResult,
    setChannelPreview,
    setError,
    setLoading,
    setPreviewLoading,
    setProgressMsg,
    setSelectedCategoryTab,
  });
  const {
    addChannelNote,
    changeNoteText,
    closeNotesModal,
    notesModal,
    openNotesModal,
  } = useChannelNotesModal({ saveChannelNote, onError: setError });
  const {
    confirmRenameCategory,
  } = useTagRenameActions({
    cancelRenameCategory,
    categories,
    loadChannelsFromCloud,
    renameValue,
    renamingCategory,
    selectedCategoryTab,
    setCategories,
    setError,
    setProgressMsg,
    setRenameLoading,
    setSelectedCategoryTab,
  });

  return {
    addChannelNote,
    addMode,
    bulkInput,
    bulkLoading,
    bulkResult,
    cancelChannelPreview,
    cancelRenameCategory,
    categories,
    changeNoteText,
    channelPreview,
    channelsLoading,
    closeNotesModal,
    confirmRenameCategory,
    deleteChannel,
    handleBulkAdd,
    handlePreviewChannel,
    handleSaveChannel,
    isEditingCategory,
    loadChannelsFromCloud,
    newCategoryName,
    newChannelInput,
    newChannelLang,
    newChannelNote,
    newChannelTags,
    notesModal,
    openNotesModal,
    previewLoading,
    renameLoading,
    renameValue,
    renamingCategory,
    resetBulkAdd,
    savedChannels,
    selectedCategoryTab,
    selectedChannelIds,
    setAddMode,
    setBulkInput,
    setCategories,
    setIsEditingCategory,
    setNewCategoryName,
    setNewChannelInput,
    setNewChannelLang,
    setNewChannelNote,
    setRenameValue,
    setSelectedCategoryTab,
    startRenameCategory,
    toggleChannelSelection,
    toggleNewChannelTag,
    updateChannelMetadata,
  };
}
