export function buildLayoutProps({
  activeCreatorItem,
  addChannelNote,
  changeNoteText,
  closeNotesModal,
  closeTopCommentsModal,
  commentModal,
  creatorView,
  discoveryCandidateCount,
  notesModal,
  openCreatorView,
  savedChannels,
  savedVideos,
  selectedChannelIds,
  syncWarnings,
  videos,
}) {
  return {
    activeCreatorItem,
    channelCount: savedChannels.length,
    commentModal,
    creatorView,
    discoveryCandidateCount,
    notesModal,
    onAddNote: addChannelNote,
    onChangeNoteText: changeNoteText,
    onCloseNotes: closeNotesModal,
    onCloseTopComments: closeTopCommentsModal,
    onOpenCreatorView: openCreatorView,
    savedVideoCount: savedVideos.length,
    selectedChannelCount: selectedChannelIds.length,
    syncWarnings,
    videoCount: videos.length,
  };
}
