export const getCreatorHomeViewProps = ({
  clearRadarDecisions,
  discoveryCandidateCount,
  discoveryRightsWarningCount,
  isVideoSaved,
  latestScanText,
  loadStoredVideosForSelectedChannels,
  markRadarVideoStatus,
  onOpenView,
  openRadarCandidateCount,
  productionCandidateCount,
  promoteVideoToProduction,
  restoreVideoToRadar,
  savedChannels,
  savedVideos,
  toggleScrapVideo,
  ttoTtoAssetCount,
  videoUserRecords,
  videos,
}) => ({
  actionShortcutsProps: {
    onOpenAddChannel: () => onOpenView({ id: 'ops-add-channel' }),
    onOpenDiscoveryLinks: () => onOpenView({ id: 'vault-sources' }),
    onOpenSelectedScan: () => onOpenView({ id: 'ops-selected-scan' }),
    onOpenVault: () => onOpenView({ id: 'vault-all' }),
  },
  radarCandidateStripProps: {
    videos,
    savedVideos,
    videoUserRecords,
    isVideoSaved,
    onToggleScrap: toggleScrapVideo,
    onMarkVideoStatus: markRadarVideoStatus,
    onPromoteToProduction: promoteVideoToProduction,
    onRestoreVideo: restoreVideoToRadar,
    onClearDecisions: clearRadarDecisions,
    onLoadStoredVideos: loadStoredVideosForSelectedChannels,
    onOpenVault: () => onOpenView({ id: 'vault-all' }),
    onOpenScrapbook: () => onOpenView({ id: 'studio-scrapbook' }),
  },
  radarSummaryProps: {
    savedChannelCount: savedChannels.length,
    loadedVideoCount: videos.length,
    savedVideoCount: savedVideos.length,
    latestScanText,
    onLoadStoredVideos: loadStoredVideosForSelectedChannels,
    ttoTtoAssetCount,
    openRadarCandidateCount,
    discoveryCandidateCount,
    discoveryRightsWarningCount,
    onOpenDiscoveryLinks: () => onOpenView({ id: 'vault-sources' }),
    onOpenProductionCandidates: () => onOpenView({ id: 'studio-candidates' }),
    productionCandidateCount,
  },
});
