export const getDiscoveryLinksWorkspaceViewProps = ({
  clearDiscoveryFilters,
  duplicateLink,
  error,
  filteredDiscoveryLinkUrlList,
  filteredLinks,
  form,
  handleSubmit,
  hasActiveDiscoveryFilters,
  isCreateDisabled,
  links,
  loading,
  notice,
  onDeleteLink,
  onRefresh,
  onUpdateLink,
  rightsFilter,
  rightsFilterOptions,
  saving,
  savingMessage,
  searchQuery,
  setRightsFilter,
  setSearchQuery,
  setStatusFilter,
  showRiskyCandidateHint,
  statusFilter,
  statusFilterOptions,
  updateForm,
  urlPreview,
}) => ({
  filtersProps: {
    filteredLinkCount: filteredLinks.length,
    hasActiveFilters: hasActiveDiscoveryFilters,
    rightsFilter,
    rightsFilterOptions,
    searchQuery,
    setRightsFilter,
    setSearchQuery,
    setStatusFilter,
    statusFilter,
    statusFilterOptions,
  },
  formProps: {
    duplicateLink,
    form,
    isCreateDisabled,
    saving,
    showRiskyCandidateHint,
    urlPreview,
    onChange: updateForm,
    onSubmit: handleSubmit,
  },
  headerProps: {
    filteredLinkCount: filteredLinks.length,
    loading,
    onRefresh,
    saving,
    totalLinkCount: links.length,
    urlList: filteredDiscoveryLinkUrlList,
  },
  listProps: {
    allLinkCount: links.length,
    clearFilters: clearDiscoveryFilters,
    filteredLinks,
    loading,
    onDeleteLink,
    onUpdateLink,
    saving,
  },
  noticesProps: {
    error,
    notice,
    savingMessage,
  },
});
