const toArray = (items) => (Array.isArray(items) ? items : []);

export const getDiscoveryLinksWorkspaceViewProps = ({
  clearDiscoveryFilters,
  duplicateLink,
  error,
  filteredDiscoveryLinkUrlList,
  filteredLinks,
  form,
  handleSubmit,
  hasActiveDiscoveryFilters,
  isCreateDisabled,
  links,
  loading,
  notice,
  onDeleteLink,
  onRefresh,
  onUpdateLink,
  rightsFilter,
  rightsFilterOptions,
  saving,
  savingMessage,
  searchQuery,
  setRightsFilter,
  setSearchQuery,
  setStatusFilter,
  showRiskyCandidateHint,
  statusFilter,
  statusFilterOptions,
  updateForm,
  urlPreview,
}) => {
  const linkList = toArray(links);
  const filteredLinkList = toArray(filteredLinks);

  return {
    filtersProps: {
      filteredLinkCount: filteredLinkList.length,
      hasActiveFilters: hasActiveDiscoveryFilters,
      rightsFilter,
      rightsFilterOptions,
      searchQuery,
      setRightsFilter,
      setSearchQuery,
      setStatusFilter,
      statusFilter,
      statusFilterOptions,
    },
    formProps: {
      duplicateLink,
      form,
      isCreateDisabled,
      saving,
      showRiskyCandidateHint,
      urlPreview,
      onChange: updateForm,
      onSubmit: handleSubmit,
    },
    headerProps: {
      filteredLinkCount: filteredLinkList.length,
      loading,
      onRefresh,
      saving,
      totalLinkCount: linkList.length,
      urlList: filteredDiscoveryLinkUrlList,
    },
    listProps: {
      allLinkCount: linkList.length,
      clearFilters: clearDiscoveryFilters,
      filteredLinks: filteredLinkList,
      loading,
      onDeleteLink,
      onUpdateLink,
      saving,
    },
    noticesProps: {
      error,
      notice,
      savingMessage,
    },
  };
};
