export function buildHomeRouteProps({
  clearRadarDecisions,
  discoveryCandidateCount,
  discoveryRightsWarningCount,
  isVideoSaved,
  latestScanText,
  markRadarVideoStatus,
  openCreatorView,
  openRadarCandidateCount,
  productionCandidateCount,
  promoteVideoToProduction,
  restoreVideoToRadar,
  savedChannels,
  savedVideos,
  toggleScrapVideo,
  ttoTtoAssetCount,
  videoUserRecords,
  videos,
}) {
  return {
    clearRadarDecisions,
    discoveryCandidateCount,
    discoveryRightsWarningCount,
    isVideoSaved,
    latestScanText,
    markRadarVideoStatus,
    onOpenView: openCreatorView,
    openRadarCandidateCount,
    productionCandidateCount,
    promoteVideoToProduction,
    restoreVideoToRadar,
    savedChannels,
    savedVideos,
    toggleScrapVideo,
    ttoTtoAssetCount,
    videoUserRecords,
    videos,
  };
}
