const toArray = (items) => (Array.isArray(items) ? items : []);

const toVideoList = (videos) => (
  toArray(videos).filter(video => video && typeof video === 'object')
);

export function getLegacyWorkspaceMainPanelViewProps({
  activeSelectedChannelCount,
  activeTab,
  checkedVideos,
  copiedPrompt,
  copyPromptForVideos,
  creatorView,
  creatorViewIntent,
  discoveryLinks,
  fetchTopComments,
  filteredAndSortedVideos,
  handleManualScan,
  isProductionCandidate,
  isReferenceVaultView,
  isScanning,
  isVideoSaved,
  lengthFilter,
  markRadarVideoStatus,
  openCreatorView,
  promoteVideoToProduction,
  promptCopyError,
  savedChannels,
  savedVideos,
  scannableChannelCount,
  searchKeyword,
  selectedChannelIds,
  setActiveTab,
  setLengthFilter,
  setSearchKeyword,
  setShowWorkPanel,
  setSortType,
  setTtoTtoMode,
  setViewFilter,
  setViewMode,
  showWorkPanel,
  sortType,
  toggleCheckVideo,
  toggleScrapVideo,
  totalVideoCount,
  ttoTtoAssetCount,
  ttoTtoMode,
  updateDiscoveryLink,
  updateVideoUserRecord,
  videoUserRecords,
  videos,
  viewFilter,
  viewMode,
  visibleScrapCount,
}) {
  const checkedVideoIds = toArray(checkedVideos);
  const filteredVideos = toVideoList(filteredAndSortedVideos);
  const savedChannelList = toArray(savedChannels);
  const savedVideoList = toVideoList(savedVideos);
  const selectedChannels = toArray(selectedChannelIds);
  const videoList = toVideoList(videos);

  return {
    activeTab,
    dashboardTabProps: {
      activeSelectedChannelCount,
      checkedVideos: checkedVideoIds,
      copiedPrompt,
      copyPromptForVideos,
      fetchTopComments,
      filteredAndSortedVideos: filteredVideos,
      handleManualScan,
      isProductionCandidate,
      isReferenceVaultView,
      isScanning,
      isVideoSaved,
      lengthFilter,
      openCreatorView,
      promoteVideoToProduction,
      promptCopyError,
      savedChannels: savedChannelList,
      savedVideos: savedVideoList,
      scannableChannelCount,
      searchKeyword,
      selectedChannelIds: selectedChannels,
      setLengthFilter,
      setSearchKeyword,
      setShowWorkPanel,
      setSortType,
      setTtoTtoMode,
      setViewFilter,
      setViewMode,
      showWorkPanel,
      sortType,
      toggleCheckVideo,
      toggleScrapVideo,
      totalVideoCount,
      ttoTtoAssetCount,
      ttoTtoMode,
      videos: videoList,
      viewFilter,
      viewMode,
      visibleScrapCount,
    },
    vaultTabProps: {
      creatorView,
      creatorViewIntent,
      discoveryLinks,
      copiedPrompt,
      copyPromptForVideos,
      fetchTopComments,
      markRadarVideoStatus,
      openCreatorView,
      promptCopyError,
      savedVideos: savedVideoList,
      toggleScrapVideo,
      updateDiscoveryLink,
      updateVideoUserRecord,
      videoUserRecords,
    },
    workspaceTabsProps: {
      activeTab,
      onSelectTab: setActiveTab,
      savedVideoCount: savedVideoList.length,
    },
  };
}
