export function getLegacyDashboardTabViewProps({
  activeSelectedChannelCount,
  checkedVideos,
  copiedPrompt,
  copyPromptForVideos,
  fetchTopComments,
  filteredAndSortedVideos,
  handleManualScan,
  isProductionCandidate,
  isReferenceVaultView,
  isScanning,
  isVideoSaved,
  lengthFilter,
  promoteVideoToProduction,
  promptCopyError,
  savedChannels,
  savedVideos,
  scannableChannelCount,
  searchKeyword,
  selectedChannelIds,
  setLengthFilter,
  setSearchKeyword,
  setShowWorkPanel,
  setSortType,
  setTtoTtoMode,
  setViewFilter,
  setViewMode,
  showWorkPanel,
  sortType,
  toggleCheckVideo,
  toggleScrapVideo,
  totalVideoCount,
  ttoTtoAssetCount,
  ttoTtoMode,
  videos,
  viewFilter,
  viewMode,
  visibleScrapCount,
}) {
  const selectedVideos = videos.filter(video => checkedVideos.includes(video.videoId));

  return {
    controlsProps: {
      activeSelectedChannelCount,
      checkedVideos,
      copiedPrompt,
      promptCopyError,
      filteredCount: filteredAndSortedVideos.length,
      filteredVideos: filteredAndSortedVideos,
      isReferenceVaultView,
      isScanning,
      lengthFilter,
      onCopyPrompt: () => copyPromptForVideos(selectedVideos),
      onManualScan: handleManualScan,
      savedChannelCount: savedChannels.length,
      savedVideoCount: savedVideos.length,
      scannableChannelCount,
      searchKeyword,
      selectedChannelCount: selectedChannelIds.length,
      setLengthFilter,
      setSearchKeyword,
      setShowWorkPanel,
      setSortType,
      setTtoTtoMode,
      setViewFilter,
      setViewMode,
      showWorkPanel,
      sortType,
      totalVideoCount,
      ttoTtoAssetCount,
      ttoTtoMode,
      viewFilter,
      viewMode,
      visibleScrapCount,
    },
    resultsPanelProps: {
      checkedVideos,
      filteredVideos: filteredAndSortedVideos,
      isProductionCandidate,
      isVideoSaved,
      onFetchComments: fetchTopComments,
      onPromoteToProduction: promoteVideoToProduction,
      onToggleCheck: toggleCheckVideo,
      onToggleScrap: toggleScrapVideo,
      showWorkPanel,
      videos,
      viewMode,
    },
  };
}
