import { isChannelScannable } from '../constants/status';
import { getChannelScanDisplay } from './channelScanDisplay';

const getScannableChannelCountForCategory = (channels, category) => (
  channels.filter(channel => (
    channel.tags?.includes(category) && isChannelScannable(channel)
  )).length
);

export function getLegacyChannelPanelViewProps({
  addMode,
  apiKey,
  bulkInput,
  bulkLoading,
  bulkResult,
  cancelChannelPreview,
  cancelRenameCategory,
  categories,
  channelPreview,
  channelsLoading,
  cloudOnlyTags,
  confirmRenameCategory,
  error,
  handleBulkAdd,
  handlePreviewChannel,
  handleSaveChannel,
  handleTagScan,
  isEditingCategory,
  isScanning,
  loading,
  newCategoryName,
  newChannelInput,
  newChannelLang,
  newChannelNote,
  newChannelTags,
  onChangeApiKey,
  onDeleteChannel,
  onLoadStoredVideos,
  onOpenNotes,
  onToggleChannelSelection,
  onUpdateChannelMetadata,
  previewLoading,
  progressMsg,
  renameLoading,
  renameValue,
  renamingCategory,
  resetBulkAdd,
  savedChannels,
  scanningTag,
  selectedCategoryTab,
  selectedChannelIds,
  setAddMode,
  setBulkInput,
  setCategories,
  setIsEditingCategory,
  setNewCategoryName,
  setNewChannelInput,
  setNewChannelLang,
  setNewChannelNote,
  setRenameValue,
  setSelectedCategoryTab,
  showWorkPanel,
  startRenameCategory,
  toggleNewChannelTag,
  updatingChannelId,
}) {
  return {
    channelAddFormProps: {
      addMode,
      bulkInput,
      bulkLoading,
      bulkResult,
      cancelChannelPreview,
      cancelRenameCategory,
      categories,
      channelPreview,
      cloudOnlyTags,
      confirmRenameCategory,
      handleBulkAdd,
      handlePreviewChannel,
      handleSaveChannel,
      isEditingCategory,
      loading,
      newCategoryName,
      newChannelInput,
      newChannelLang,
      newChannelNote,
      newChannelTags,
      previewLoading,
      renameLoading,
      renameValue,
      renamingCategory,
      resetBulkAdd,
      setAddMode,
      setBulkInput,
      setCategories,
      setIsEditingCategory,
      setNewCategoryName,
      setNewChannelInput,
      setNewChannelLang,
      setNewChannelNote,
      setRenameValue,
      startRenameCategory,
      toggleNewChannelTag,
    },
    channelListProps: {
      channels: savedChannels,
      channelsLoading,
      getScanDisplay: getChannelScanDisplay,
      onDelete: onDeleteChannel,
      onOpenNotes,
      onToggleSelection: onToggleChannelSelection,
      onUpdateMetadata: onUpdateChannelMetadata,
      selectedCategory: selectedCategoryTab,
      selectedChannelIds,
      updatingChannelId,
    },
    footerProps: {
      error,
      loading,
      onLoadStoredVideos,
      progressMsg,
      selectedChannelCount: selectedChannelIds.length,
    },
    introProps: {
      apiKey,
      onChangeApiKey,
    },
    showWorkPanel,
    tagTabsProps: {
      categories,
      channels: savedChannels,
      getScannableChannelCount: (category) => getScannableChannelCountForCategory(savedChannels, category),
      isScanning,
      onScanTag: handleTagScan,
      onSelectCategory: setSelectedCategoryTab,
      scanningTag,
      selectedCategory: selectedCategoryTab,
    },
  };
}
